// mock-fe/angular-mock-hello-world/src/app/portal/portal.component.ts
import { Component, OnInit, Inject, ViewChild } from '@angular/core';
import { DOCUMENT } from '@angular/common';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Router } from '@angular/router';
import { NgxCumulioDashboardComponent } from '@cumul.io/ngx-cumulio-dashboard';

@Component({
  selector: 'app-portal',
  templateUrl: './portal.component.html',
  styleUrls: ['./portal.component.scss']
})
export class PortalComponent implements OnInit {

  @ViewChild('dashboardInstance') dashboardInstance?: NgxCumulioDashboardComponent;

  dashboardId: string | undefined ='';
  appServer='APP_SERVER_HERE';
  apiHost='API_HOST_HERE';
  key?: string;
  token?: string;

  userAuthToken?: string;
  user?: {
    username: string;
    email: string;
    brand: string;
  }

  constructor(@Inject(DOCUMENT) public document: Document, private http: HttpClient, private router: Router) {}

  ngOnInit(): void {
    // We can use raw claims to send JWT token instead of cumulio object.
    const token = window.localStorage.getItem('authorization');

    if (token) {
      this.userAuthToken = token as string;
      this.user = this.parseJwt(token as string);
      // do an API call to authorize.
      this.http.get<{
        status: string;
        key?: string;
        token?: string;
      }>(`http://localhost:4001/`, {
        headers: {
          'authorization': 'Bearer ' + token as string 
        }
      })
      .subscribe((data) => {
        console.log(data);
        this.key = data.key;
        this.token = data.token;
        setTimeout(() => {
          // dynamically fetch dashboards and load the first one
          this.dashboardInstance?.getAccessibleDashboards().subscribe(dashboards => {
            this.dashboardId = dashboards[0]?.id;
          });
        }, 100);
      });
    } else {
      this.router.navigateByUrl('/');
    }
  }

  logout() {
    window.localStorage.removeItem('authorization');
    this.router.navigateByUrl('/');
  }

  parseJwt (token: string) {
    var base64Url = token.split('.')[1];
    var base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
    var jsonPayload = decodeURIComponent(window.atob(base64).split('').map(function(c) {
        return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
    }).join(''));

    return JSON.parse(jsonPayload);
  }

}

<div *ngIf="userAuthToken else loader" class="position-relative">
  <nav class="navbar navbar-dark" [ngStyle]="{
    'background-color': user?.brand === 'Mars Boots' ? '#f06292' : '#d32f2f'
  }">
    <div class="container">
      <a class="navbar-brand" href="#">{{ user?.brand === 'Mars Boots'  ? 'MARS BOOTS' : 'EARTHLY SHOES'}}</a>
      <span class="d-flex navbar-email position-relative">
        <strong>{{user?.email}}</strong>
        <div *ngIf="userAuthToken" class="position-absolute btn btn-dark btn-logout" (click)="logout()">Logout</div>
      </span>
    </div>
  </nav>
  <div class="container mt-4">
    <cumulio-dashboard
      #dashboardInstance
      *ngIf="key && token"
      [dashboardId]="dashboardId"
      [authKey]="key"
      [authToken]="token"
      [appServer]="appServer"
      [apiHost]="apiHost"
    >
    </cumulio-dashboard>
  </div>
</div>
<ng-template #loader>
  <div class="spinner-border text-danger loader" role="status">
    <span class="visually-hidden">Loading...</span>
  </div>
</ng-template>

// mock-fe/react-mock-hello-world/src/portal/Portal.tsx
import { Link, useNavigate } from "react-router-dom";
import { useEffect, useState, useRef } from 'react';
import { CumulioDashboardComponent, CumulioDashboard } from "@cumul.io/react-cumulio-dashboard";
import { parseJwt } from '../global';
import './portal.css';

const appServer = 'APP_SERVER_HERE';
const apiHost = 'API_HOST_HERE';

function Portal() {
  const [dashboardId, setDashboardId] = useState<string | undefined>('');
  const navigate = useNavigate();
  const [key, setKey] = useState<string | null>(null);
  const [token, setToken] = useState<string | null>(null);
  const [user, setUser] = useState<{email?: string; username?: string; brand?: string;}>({});
  const ref = useRef<CumulioDashboard>(null);
  useEffect(() => {
    const authorization = window.localStorage.getItem('authorization');
    setUser(parseJwt(authorization as string));
    if (authorization) {
      window.fetch(`http://localhost:4001`, {
        headers: {
          'authorization': 'Bearer ' + authorization
        }
      })
      .then(response => response.json())
      .then(data => {
        setTimeout(() => {
          setKey(data.key);
          setToken(data.token);
          console.log(data, key, token);
          setTimeout(() => {
            ref.current?.getAccessibleDashboards().then(dashboards => {
              console.log(dashboards);
              if (dashboards) {
                setDashboardId(dashboards[0]?.id);
              }
            });
          }, 100);
        }, 2000);

      });
    }
  }, []);

  function logout() {
    window.localStorage.removeItem('authorization');
    navigate('/', { replace: true });
  }


  return user ? <div className="position-relative">
    <nav className="navbar navbar-dark" style={{
      'backgroundColor': user?.brand === 'Mars Boots' ? '#f06292' : '#d32f2f'
    }}>
      <div className="container">
        <Link className="navbar-brand" to="#">{ user?.brand === 'Mars Boots'  ? 'MARS BOOTS' : 'EARTHLY SHOES'}</Link>
        <span className="d-flex navbar-email position-relative">
          <strong>{user?.email}</strong>
          <div className="position-absolute btn btn-dark btn-logout" onClick={() => logout()}>Logout</div>
        </span>
      </div>

    </nav>
    <div className="container mt-4 position-relative dashboard-loader">
    { key && token ? <CumulioDashboardComponent
      ref={ref}
      dashboardId={dashboardId}
      authKey={key}
      authToken={token}
      appServer={appServer}
      apiHost={apiHost}
      mainColor="pink"
      accentColor="black"
      loaderSpinnerColor="rgb(0, 81, 126)"
      loaderSpinnerBackground="rgb(236 248 255)"
      itemsRendered={(e) => console.log("itemsRendered", e)}
      exported={(e) => console.log("exported", e)}
      load={(e) => console.log("load", e)}
    ></CumulioDashboardComponent> : <div className="spinner-border text-danger loader" role="status">
    <span className="visually-hidden">Loading...</span>
  </div> }
    </div>
    </div> : <div className="spinner-border text-danger loader" role="status">
    <span className="visually-hidden">Loading...</span>
  </div>;
}

export default Portal;
