// mock-fe/react-mock-hello-world/src/login/login.tsx
import { Link, useNavigate } from 'react-router-dom';
import './login.css';
import { useState } from 'react';

function Login() {
  const navigate = useNavigate();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  function login(username?: string) {
    let emailId = email;
    let passwordLocal = password;
    if (username === 'brad') {
      emailId = 'brad@mars-boots.com';
      passwordLocal = 'brad';
    } else if (username === 'angelina') {
      emailId = 'angelina@earthly-shoes.com';
      passwordLocal = 'angelina';
    }
    setEmail(emailId);
    setPassword(passwordLocal);

    console.log(emailId, passwordLocal);
    window.fetch(`http://localhost:4001/login`, {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        email: emailId,
        password: passwordLocal
      })
    })
    .then(res => res.json())
    .then((data) => {
      console.log(data);
      window.localStorage.setItem('authorization', data.token as string);
      navigate('/portal', { replace: true });
    });
  }

  return <div>
    <div className="position-relative">
      <nav className="navbar navbar-dark" style={{
        'backgroundColor': '#ab47bc'
      }}>
        <div className="container">
          <Link className="navbar-brand" to="/">UNIVERSAL SHOES</Link>
          <span className="d-flex navbar-investor position-relative">
          </span>
        </div>

      </nav>
    </div>
    <div className="login-page">
      <div className="row justify-content-center align-center mb-2">
        <div
          className="col-5 text-center btn btn-outline-danger mx-2"
          id="login-as-brad"
          onClick={e => login('brad')}
        >
          Login as Brad
        </div>
        <div
          className="col-5 text-center btn btn-outline-warning mx-2"
          id="login-as-angelina"
          onClick={e => login('angelina')}
        >
          Login as Angelina
        </div>
      </div>
      <div className="form">
        <form className="login-form">
          <input type="email" placeholder="email" name="email" id="email" value={email} onChange={e => setEmail(e.target.value)}/>
          <input type="password" placeholder="password" name="password" id="password" value={password} onChange={e => setPassword(e.target.value)} />
          <div className="btn btn-primary login-button" id="login-btn" onClick={e => login()}>login</div>
        </form>
      </div>
    </div>
  </div>;
}

export default Login;

// mock-fe/angular-mock-hello-world/src/app/login/login.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  email = '';
  password = '';

  constructor(private http: HttpClient, private router: Router) { }

  ngOnInit() {
  }

  login(username?: string) {
    console.log(this.email, this.password);
    if (username === 'brad') {
      this.email = 'brad@mars-boots.com';
      this.password = 'brad';
    } else if (username === 'angelina') {
      this.email = 'angelina@earthly-shoes.com';
      this.password = 'angelina';
    }
    this.http.post<{
      token?: string;
    }>(`http://localhost:4001/login`, {
      email: this.email,
      password: this.password
    })
    .subscribe((data) => {
      console.log(data);
      window.localStorage.setItem('authorization', data.token as string);
      this.router.navigateByUrl('/portal');
    });
  }

}

<div class="position-relative">
  <nav class="navbar navbar-dark" [ngStyle]="{
    'background-color': '#ab47bc'
  }">
    <div class="container">
      <a class="navbar-brand" href="#">UNIVERSAL SHOES</a>
      <span class="d-flex navbar-investor position-relative">
      </span>
    </div>

  </nav>
</div>

<div class="login-page">
  <div class="row justify-content-center align-center mb-2">
    <div
      class="col-5 text-center btn btn-outline-danger mx-2"
      (click)="login('brad')"
    >
      Login as Brad
    </div>
    <div
      class="col-5 text-center btn btn-outline-warning mx-2"
      (click)="login('angelina')"
    >
      Login as Angelina
    </div>
  </div>
  <div class="form">
    <form class="login-form">
      <input type="email" placeholder="email" name="email" [(ngModel)]="email"/>
      <input type="password" placeholder="password" name="password" [(ngModel)]="password" />
      <div class="btn btn-primary login-button" (click)="login()">login</div>
    </form>
  </div>
</div>
